// pinia/vue_pinia/src/components/ListPlayers.vue
<!-- 

  Copy paste your code from the ListPlayers.vue file here from the players_CRUD exercise of the Vue week.

  BEWARE: No props are passed to this component from now on. Instead, all the needed data is fetched and updated in the Pinia store. Therefore, use it to get the players array from the store.
 -->
<template></template>

<script></script>

// redux/react_redux/src/components/ListPlayers.jsx
/** @format */

/** @format
 * @description
 * Student instructions:
 *
 * Copy paste your code from the ListPlayers.jsx file here from the react player fetch exercise
 * BEWARE: Only the selectPlayer function is passed as a prop from now on. The players data is fetched from the redux store.
 *
 */
export const ListPlayers = ({ selectPlayer }) => {
  return (
    <div>
      <h2>List of players</h2>
      TODO: ListPlayers
    </div>
  );
};
