// react/players_fetch/src/components/SelectedPlayer.jsx
/* eslint-disable react/prop-types */

/** @format
 *
 * Student instructions:
 * This component is used to display the selected player. It receives a player as props.
 * 
 * Create the component that you did in Vue now with React. Use provided props to handle user events. 
 * Find and replace functionality with React equivalents.

 * NOTE: use the same ids, classes and html elements as you did in Vue. Refer to tests 
in the __tests__ folder to pass the unit tests, and to the cypress/e2e folder for the end-to-end tests.
 */
export const SelectedPlayer = ({ player }) => {
  if (!player) {
    return null;
  }

  return (
    <div id="selected-player">
      <h2>Selected Player</h2>
      <p id="player-name">{player.name}</p>
      <p id="player-status">{player.isActive ? "active" : "inactive"}</p>
    </div>
  );
};

// vue/players_fetch/src/components/SelectedPlayer.vue
<!-- 
  Useful to read:
  https://vuejs.org/guide/scaling-up/sfc.html
  https://vuejs.org/guide/essentials/conditional.html

  Student instructions:

  This component is used to display the selected player. It receives a player prop.

  Create an element with an id attribute set to "selected-player", and inside it create two more elements, one with an id attribute set to "player-name" and another with an id attribute set to "player-status"

  Display the value of the name property of the player prop inside the element with the id of "player-name" 

  Display the value of the isActive property of the player prop inside the element with the id of "player-status". If the value of the isActive property is true, display the text "active". If the value of the isActive property is false, display the text "inactive".

  Use template logic to check if the player prop is null or not. If it is null, don't render the component.
 -->

 <template v-if="player">
    <div v-if="player" id="selected-player">
      <h1>Selected Player</h1>
      <p id="player-name" >
        {{ player.name }}
      </p>
      <div id="player-status">
        <p  v-if="player.isActive">
          active
        </p>
        <p v-else>
          inactive
        </p>
      </div>
    </div>
 </template>



<script>
export default {
  props: ['player']
}
</script>
