// vue/players_CRUD2/src/components/AddPlayer.vue
<!-- 
  Copy paste your code from the ListPlayer.vue file here from the previous exercise. No changes are needed if you managed to get the component to work properly in the previous exercise.
 -->


 <template>
  <div>
    <h2>Add Player</h2>
    <form id="submit-player" @submit.prevent ="handleSubmit">
      <input id="input-player" placeholder="Enter name" v-model="name"/>
      <button class="btn-add" type="submit">Add</button>
    </form>
  </div>
</template>

<script>
export default {
  data () {
    return {
      name: ""
    }
},
methods: {
  handleSubmit() {
    this.$emit('add-player', this.name)
    this.name = "";
  }
}
}

</script>

// react/players_CRUD2/src/components/AddPlayer.jsx
/** @format
 *
 * Student instructions:
 *
 * COPY YOUR CODE FROM THE PREVIOUS EXERCISE HERE.
 */

import { useState } from "react";

export const AddPlayer = ({handleSubmit}) => {
  const [name, setName ]= useState("");

  const handleNameChange = (e) => {
    e.preventDefault();
    setName(e.target.value);
  }

  const handleSubmitForm = (e) => {
    e.preventDefault();
    if (name.trim() !== "") {
      handleSubmit(name);
      setName(""); 
    }
  };

  return <div>
    <form id="submit-player" onSubmit={handleSubmitForm}>
      <input id="input-player" placeholder="Enter name" type="text" onChange={handleNameChange} value={name}/>
      <button className="btn-add" type="submit">Add</button>
    </form>
  </div>;
};
