// redux/redux_thunk/src/components/RequestStatus.jsx
/** @format
 * Copy paste your code from the RequestStatus.jsx file here from the previous exercise
 *
 * BEWARE: No props are passed to this component from now on. Instead, all the data is fetched and updated in the redux store.
 */
export const RequestStatus = () => {
	return (
		<div>
			<h3>Request status</h3>
			TODO RequestStatus
		</div>
	);
};

// vue/players_CRUD/src/components/RequestStatus.vue
<!-- 
  Copy paste your code from the ListPlayer.vue file here from the previous exercise. No changes are needed if you managed to get the component to work properly in the previous exercise.
 -->


 <template> 
  <h2>Request Status</h2>
  <div id="request-status">
    {{ reqStatus }}
  </div>
</template>

<script>
export default {
  props: ["reqStatus"],
};
</script>
