// pinia/vue_pinia/src/App.vue
<!-- 
 * You can copy paste the App.vue file logic from the players-CRUD Vue-exercise to get started. In this exercise, you will be introducing pinia, which is a Vue 3 store that is inspired by Vuex. You will be using pinia to manage the state of the application.
 *
 * Since all the state will be managed by pinia, you will need to remove the state management code from the App.vue file. You will also need to remove the fetch functions from the App.vue file. The fetch functions will be moved into Pinia's store. Each action in pinia will be responsible for handling the request while keeping the application up to date with loading, success, and failure actions. You can name the action creators anything, but it is recommended to name them based on the component that will be using them.
 *
 * You can find the template file for the store in src/pinia/playerStore.js. You will need to create the actions to handle the HTTP requests, and getters to access the store data. You will also need to create the getters to get the state of the application.

 Once you are finished, the Application should still work the same way as it did before, meaning you can add, delete, and select players. The only difference is that the state will be managed by pinia.
 -->

<template>
  <AppTitle />
  <!-- No need to touch this component -->
  <RequestStatus />
  <!-- No longer being passed props or slots -->
  <AddPlayer />
  <!-- No longer being passed props or slots -->
  <ListPlayers />
  <!-- No longer being passed props or slots -->
  <SelectedPlayer />
  <!-- No longer being passed props or slots -->
</template>

<script>
import AddPlayer from "./components/AddPlayer.vue";
import ListPlayers from "./components/ListPlayers.vue";
import ListPlayer from "./components/ListPlayer.vue";
import SelectedPlayer from "./components/SelectedPlayer.vue";
import RequestStatus from "./components/RequestStatus.vue";
import AppTitle from "./AppTitle.vue";

export default {
  components: {
    AddPlayer,
    ListPlayers,
    ListPlayer,
    SelectedPlayer,
    RequestStatus,
    AppTitle,
  },
};
</script>

// redux/react_redux/src/App.jsx
/** @format 
 * 
 * Student instructions:
 * Copy paste the App.jsx file from the previous exercises into this file. In this exercise, you will be introducing redux, which is a state management library that allows you to manage the state of your application in a single store. The store is a single source of truth for the state of your application, and it is the only place where the state can be updated. 
 * 
 * The fetch functions will start using action creators from now on. Each action creator will be responsible for updating the redux store with the data from the request. You can find the template files for the action creators in the src/redux/actionCreators folder. It is your job to implement them, as well as the reducers that will be used to update the store. The reducers can be found in the src/redux/reducers folder.
 * 
  Hint: Use the provided REQ_STATUS object to update the request status when necessary. "loading" for when the request is in progress, "success" for when the request is successful, and "error" for when the request has failed. The REQ_STATUS object is imported from the "../cypress/e2e/constants.js" file.

*/

import { ListPlayers } from "./components/ListPlayers.jsx";
import { SelectedPlayer } from "./components/SelectedPlayer.jsx";
import { RequestStatus } from "./components/RequestStatus.jsx";
import { REQ_STATUS } from "../cypress/e2e/constants.js";

function App() {
  return (
    <>
      <RequestStatus />
      <ListPlayers />
      <SelectedPlayer />
    </>
  );
}

export default App;
