// vue/players_fetch/src/App.vue
<!-- 
  The Vue projects for this course are expected to be made using Single File Components (SFCs). You can get started by going through the following sections from the Vue documentation (https://vuejs.org/guide/introduction.html):
  - Getting Started
  - Essentials
  - Components In-Depth

  Once you are familiar with the basics of Vue, you can start working on the project. The project is divided into 4 parts, each with its own set of instructions. The first part is the main component of the application, the second part is the component (and its child component) that displays the list of players, and the third part is the component that displays the selected player. The fourth part is displaying the status of the request to the API.

  Student instructions:

  This is the main component of the application. It is used to fetch and store the players data upon creation, and to display the list of players and the selected player.

  1. Inside the root div element, import and add the  RequestStatus, ListPlayers, and SelectedPlayer components as child elements. Remember to pass in the appropriate props and content to the child components.

  2. Create two methods for fetching all players and fetching one specific player. The first method should handle the logic for fetching all the players and displaying them in the players array. The second method should handle the logic for fetching a specific player. Use the REQ_STATUS object to display the appropriate status message when the request is loading, when it is successful, and when it fails. 
  
  The URLS for fetching all players and fetching a specific player remain the same throughout the course (http://localhost:3001/api/players, http://localhost:3001/api/players/:id). Once the backend is running, you can visit http://localhost:3001 to see the API documentation.

  3. Whenever the page is refreshed, fetch players data, store and display it.
 -->


 <template>
  <div id="app">
    <RequestStatus :reqStatus="reqStatus"/>
    <ListPlayers :players="players" :getPlayer="fetchPlayer"/>
    <SelectedPlayer :player="activePlayer"/>
  </div>
</template>

<script>
import RequestStatus from './components/RequestStatus.vue';
import ListPlayers from './components/ListPlayers.vue';
import SelectedPlayer from './components/SelectedPlayer.vue';


const REQ_STATUS = {
  loading: "Loading...",
  success: "Finished!",
  error: "An error has occurred!!!",
};

export default {
  data () {
    return {
      players: [],
      reqStatus: null,
      activePlayer: null
    }
  },
  components: {
    RequestStatus,
    ListPlayers,
    SelectedPlayer
  },
  created(){
    this.fetchAllPlayers();
    
  },
  methods: {
    async fetchAllPlayers () {
      try {
        this.reqStatus = REQ_STATUS.loading

        const response = await fetch('http://localhost:3001/api/players');
        if (!response.ok) {
          this.reqStatus= REQ_STATUS.error;
          throw new Error("Couldn't fetch data.")
        }
        const data = await response.json();
        this.players = data;
        this.reqStatus = REQ_STATUS.success;

      } catch (err) {
        console.error(err);
      }
    },
    async fetchPlayer (id) {
      try {
        this.reqStatus = REQ_STATUS.loading

        const response = await fetch(`http://localhost:3001/api/players/${id}`);
        if (!response.ok) {
          this.reqStatus = REQ_STATUS.error;
          throw new Error("Couldn't fetch player.")
        }
        const data = await response.json();

        console.log(data);
        this.activePlayer = data;
        this.reqStatus = REQ_STATUS.success;


      } catch (err) {
        console.error(err);
      }
    }
  },

  

};
</script>

// react/players_fetch/src/App.jsx
/** @format 
 * 
 * Useful to read:
 * https://react.dev/
 * 
 * Student instructions:
 * Use the provided components to create a React app that fetches players from the provided API and displays them in a list when the App is first rendered. 
 * When a player is clicked in the list, fetch that player and display it in the selected player section.
 *  Give ListPlayer a function as its selectPlayer prop: it is used to fetch a specific player and should take a player id as its only argument. 
 * 
 * You can use the Vue exercise players_fetch as a reference and inspiration. More detailed descriptions of the components 
 * can also be found in the Vue exercises, but the components are not exactly the same.

	* REMEMBER: use the same ids, classes and attributes as in the Vue exercise in the same places to pass the tests. Remember to pass in the appropriate props to the child components.

	* BEWARE: The component props may be different from the Vue exercise and the tests will not pass if you use the wrong props.
	
  Hint: Use the provided REQ_STATUS object to update the request status when necessary. Use "loading" key for when the request 
  is in progress, "success" key for when the request is successful, and "error" for when the request has failed. 
  The REQ_STATUS object is now imported from the ../cypress/e2e/constants.js file and should not be modified.

*/

const url = "http://localhost:3001/api/players";
import { REQ_STATUS } from "../cypress/e2e/constants.js";
import { ListPlayers } from "./components/ListPlayers.jsx";
import { SelectedPlayer } from "./components/SelectedPlayer.jsx";
import { RequestStatus } from "./components/RequestStatus.jsx";
import { useEffect, useState } from "react";

function App() {
  const [ players, setPlayers ] = useState(null);
  const [ player, setPlayer ] = useState(null);

  const [ loading, setLoading ] = useState(true);


  useEffect(() => {
    const fetchPlayers = async () => {
      try {
        setLoading(true);

        const response = await fetch(url);
        if (!response.ok) {
          throw new Error("Couldnt fetch players");
        }
        const data = await response.json();
        setLoading(false);
        setPlayers(data);
      } catch (err) {
        setLoading(null);
        console.error(err);
      }
    }
    fetchPlayers();
  },[])


  const getPlayer = async (id) => {
    try {
      setLoading(true);

      const response = await fetch(url+'/'+id);
      if (!response.ok) {
        throw new Error("Couldnt fetch player");
      }
      const data = await response.json();
      setLoading(false);
      setPlayer(data);
    } catch (err) {
      setLoading(null);
      console.error(err);
    }
  }

  return (
    <div>
      <h2>Request Status</h2>
      <RequestStatus reqStatus={loading ? REQ_STATUS.loading : (loading === false ? REQ_STATUS.success : REQ_STATUS.error)} />
      <h2>List of players</h2>
      <ListPlayers players={players} getPlayer={getPlayer}/>
      <SelectedPlayer player={player} />
    </div>
  )
}

export default App;
